name: build-test
description: Build & run unit and Cypress tests

runs:
  using: composite
  steps:
    - name: Build packages
      run: pnpm -r build
      shell: bash
      env:
        VITE_API_URL: http://localhost:7180

    # - name: Run type check and unit tests
    #   run: |
    #     pnpm --filter client svelte-check
    #     pnpm --filter client test:unit
    #   shell: bash

    - name: Run tests with Cypress
      id: cypress
      uses: cypress-io/github-action@v5
      with:
        browser: chrome
        cache-key: ${{ runner.os }}-node-${{ matrix.node-version }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        command: pnpm --filter e2e test
        install: false
        quiet: false
        start: pnpm --filter client dev --host
        wait-on: http://127.0.0.1:5577
        working-directory: ./packages/e2e
      env:
        VITE_API_URL: http://localhost:7180

    - name: Export screenshots (on failure only)
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-screenshots
        path: |
          ./packages/e2e/cypress/screenshots
          ./packages/e2e/cypress/e2e/**/*.png
        retention-days: 7

    - name: Export screen recordings (on failure only)
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-videos
        path: ./packages/e2e/cypress/videos
        retention-days: 7
