name: build-test
description: Build & run unit and Cypress tests

runs:
  using: composite
  steps:
    - name: Build packages
      run: pnpm -r build
      shell: bash
      env:
        VITE_API_URL: https://example-api.teemukoivisto.xyz

    - name: Run type check and unit tests
      run: |
        pnpm --filter sveltekit-monorepo-template svelte-check
        pnpm --filter sveltekit-monorepo-template test:unit
      shell: bash

    # - name: Run tests with Cypress
    #   id: cypress
    #   uses: cypress-io/github-action@v2
    #   with:
    #     install: false # Don't install Cypress again
    #     cache-key: ${{ runner.os }}-node-${{ matrix.node-version }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
    #     command: pnpm --filter sveltekit-monorepo-template test:e2e
    #     start: pnpm --filter site start
    #     wait-on: 'http://localhost:5715/sveltekit-monorepo-template'
    #     project: ./packages/sveltekit-monorepo-template
    #     browser: chrome
    #     quiet: true
    #   env:
    #     SKIP_PREFLIGHT_CHECK: true

    # - name: Export screenshots (on failure only)
    #   uses: actions/upload-artifact@v2.2.3
    #   if: failure()
    #   with:
    #     name: cypress-screenshots
    #     path: ./packages/sveltekit-monorepo-template/cypress/screenshots
    #     retention-days: 7

    # - name: Export screen recordings (on failure only)
    #   uses: actions/upload-artifact@v2.2.3
    #   if: failure()
    #   with:
    #     name: cypress-videos
    #     path: ./packages/sveltekit-monorepo-template/cypress/videos
    #     retention-days: 7
