name: Build and test pull requests

on: [pull_request, workflow_dispatch]

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - name: Setup pnpm
        uses: ./.github/actions/pnpm

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build packages
        run: |
          pnpm --filter types --filter utils build --filter db build && \
          pnpm --filter client --filter api build
        env:
          VITE_API_URL: https://api.teemukoivisto.xyz/sveltekit-monorepo

      - name: Build & test
        uses: ./.github/actions/e2e
